### ISSUE TITLE
example generation

### ISSUE THREAD

**Issue by Thornhill-GYL** [YJiangcm/Lion#6]
hi, thanks for release your code. i would like to ask why you concat all the instruction and input in the prompt to get the new prompt? 
looking forward to your reply. thanks.

**Comment by YJiangcm** [comment]
Thanks for your question. The function `encode_prompt` in src/generate_hard_instruction.py indeed supports concatenating several instructions to get the new prompt. But in our implementation, we set `num_prompt_instructions=1` to use only one instruction for obtaining the new prompt.

**Comment by Thornhill-GYL** [comment]
thanks for your reply
